sudo: false
language: node_js
node_js: 
  - "9"
script:
  - npm run lint
  - npm test
  - npm run build
deploy:
  provider: heroku
  app: bcg-messenger
  api_key: 
    secure: "b84a8f5e-0a9f-4112-88b1-c72e28483304"
